apiVersion: apps/v1
kind: Deployment
metadata:
  name: facedetected-node01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facedetected-node01
  template:
    metadata:
      labels:
        app: facedetected-node01
      annotations:
        ovn.kubernetes.io/ip_pool: 10.16.11.11
    spec:
      nodeName: node01
      tolerations:
      - key: node-role.kube-ovn/master  
        effect: NoSchedule
      containers:
      - name: facedetected-node01
        image: hokuanyu/facedetected
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: facedetected-node02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facedetected-node02
  template:
    metadata:
      labels:
        app: facedetected-node02
      annotations:
        ovn.kubernetes.io/ip_pool: 10.16.11.12
    spec:
      nodeName: node02
      tolerations:
      - key: node-role.kube-ovn/master  
        effect: NoSchedule
      containers:
      - name: facedetected-node02
        image: hokuanyu/facedetected
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: facedetected-node03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facedetected-node03
  template:
    metadata:
      labels:
        app: facedetected-node03
      annotations:
        ovn.kubernetes.io/ip_pool: 10.16.11.13
    spec:
      nodeName: node03
      tolerations:
      - key: node-role.kube-ovn/master  
        effect: NoSchedule
      containers:
      - name: facedetected-node03
        image: hokuanyu/facedetected
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: facedetected-node04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facedetected-node04
  template:
    metadata:
      labels:
        app: facedetected-node04
      annotations:
        ovn.kubernetes.io/ip_pool: 10.16.11.14
    spec:
      nodeName: node04
      tolerations:
      - key: node-role.kube-ovn/master  
        effect: NoSchedule
      containers:
      - name: facedetected-node04
        image: hokuanyu/facedetected
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: facedetected-node05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facedetected-node05
  template:
    metadata:
      labels:
        app: facedetected-node05
      annotations:
        ovn.kubernetes.io/ip_pool: 10.16.11.15
    spec:
      nodeName: node05
      tolerations:
      - key: node-role.kube-ovn/master  
        effect: NoSchedule
      containers:
      - name: facedetected-node05
        image: hokuanyu/facedetected
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: facedetected-node06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facedetected-node06
  template:
    metadata:
      labels:
        app: facedetected-node06
      annotations:
        ovn.kubernetes.io/ip_pool: 10.16.11.16
    spec:
      nodeName: node06
      tolerations:
      - key: node-role.kube-ovn/master  
        effect: NoSchedule
      containers:
      - name: facedetected-node06
        image: hokuanyu/facedetected
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
